Repository reinfer/cli, pull requests merged in 2020-09, with the labels that each got.

#25 ci: Add clippy as separate job
  .github/workflows/rust.yml
  cli/src/commands/create/comments.rs
Labels: code health

#26 chore: update deps, add dependabot config
  .github/dependabot.yml
  CHANGELOG.md
  Cargo.lock
  cli/Cargo.toml
Labels: dependencies

#24 task: Add retry on timeout for multi-request cmds
  CHANGELOG.md
  Cargo.lock
  api/Cargo.toml
  api/src/lib.rs
  api/src/retry.rs
  cli/src/main.rs
Labels: enhancement

#29 api: use new query format for comment uid lists
  api/src/lib.rs
Labels: enhancement
