Repository reinfer/cli, pull requests merged in 2021-02, with the labels that each got.

#45 deps: updates for feb 2021
  Cargo.lock
  api/Cargo.toml
  cli/Cargo.toml
Labels: dependencies

#47 Replace failure crate with anyhow/thiserror
  .github/workflows/rust.yml
  CHANGELOG.md
  Cargo.lock
  api/Cargo.toml
  api/src/error.rs
  api/src/errors.rs
  api/src/lib.rs
  api/src/resources/bucket.rs
  api/src/resources/comment.rs
  api/src/resources/dataset.rs
  api/src/resources/mod.rs
  api/src/resources/source.rs
  api/src/resources/trigger.rs
  api/src/resources/user.rs
  cli/Cargo.toml
  cli/src/args.rs
  cli/src/commands/config.rs
  cli/src/commands/create/bucket.rs
  cli/src/commands/create/comments.rs
  cli/src/commands/create/dataset.rs
  cli/src/commands/create/emails.rs
  cli/src/commands/create/mod.rs
  cli/src/commands/create/source.rs
  cli/src/commands/create/user.rs
  cli/src/commands/delete.rs
  cli/src/commands/get.rs
  cli/src/commands/mod.rs
  cli/src/config.rs
  cli/src/errors.rs
  cli/src/main.rs
  cli/src/utils.rs
  cli/tests/common.rs
  cli/tests/test_comments.rs
Labels: code health

#48 Allow users to specify EntityDef-s at dataset creation
  api/src/error.rs
  api/src/resources/comment.rs
  api/src/resources/dataset.rs
  cli/src/commands/create/dataset.rs
Labels: enhancement
